# =================================================
# Lifecycle Manager
# =================================================
lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ['map_server', 'amcl']

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      ['controller_server', 'planner_server', 'behavior_server', 'bt_navigator']

# =================================================
# Map Server
# =================================================
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/zero/maze.yaml"
    frame_id: "map"

# =================================================
# AMCL
# =================================================
amcl:
  ros__parameters:
    use_sim_time: true
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "scan"
    laser_frame_id: "base_scan"
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0

# =================================================
# Global Costmap
# =================================================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.105
      resolution: 0.05

      plugins: ["static_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        subscribe_to_updates: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35
        cost_scaling_factor: 3.0

# =================================================
# Local Costmap
# =================================================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true

      width: 4
      height: 4
      resolution: 0.05
      robot_radius: 0.105

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan

        scan:
          topic: /scan
          data_type: "LaserScan"
          clearing: true
          marking: true
          obstacle_range: 3.0
          raytrace_range: 3.5
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 3.0

# =================================================
# Planner Server
# =================================================
planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

# =================================================
# Controller Server (Regulated Pure Pursuit)
# =================================================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 15.0

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      desired_linear_vel: 0.22
      min_linear_vel: 0.05
      max_linear_accel: 0.5
      max_linear_decel: 0.5

      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      use_velocity_scaled_lookahead_dist: true

      rotate_to_heading_angular_vel: 1.8
      allow_reversing: false

      transform_tolerance: 0.1

      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0

# =================================================
# BT Navigator
# =================================================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_frame: odom
    bt_loop_duration: 10
    default_server_timeout: 20
    default_bt_xml_filename:
      "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"

# =================================================
# Behavior Server
# =================================================
behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "wait"]

    spin:
      plugin: "nav2_behaviors/Spin"

    backup:
      plugin: "nav2_behaviors/BackUp"

    wait:
      plugin: "nav2_behaviors/Wait"



